name:                calico 
version:             0.2.1.0
github:              "ix/calico"
license:             BSD3
author:              "Rose"
maintainer:          "rose@empty.town"
copyright:           "2019 Rose"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/palm#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.13.2 && < 0.14
- optparse-applicative >= 0.14.3 && < 0.15
- hspec >= 2.6.0 && < 2.7.1
- bytestring >= 0.10.8 && < 0.11
- safe >= 0.3.17 && < 0.4

library:
  source-dirs: src

executables:
  calico:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - calico

tests:
  calico-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calico 
    - QuickCheck
